name: Publish package to NPM Registry

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Use Classic Yarn
        run: yarn set version classic

      - name: Install dependencies
        run: yarn install --force --frozen-lockfile --production=false

      - name: Run linters
        run: yarn lint

      - name: Run Tests
        run: yarn test

      - name: See contents of packed
        run: |
          echo "PACKED=$(yarn pack:list)" >> $GITHUB_ENV
          echo "${{ env.PACKED }}"
